name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  cpu-test:
    runs-on: ubuntu-20.04
    container:
      image: dreamer2368/magudi_env:latest
      options: --user 1001 --privileged
    name: Optimization-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Cmake
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=debug -DCMAKE_Fortran_COMPILER=mpif90 ../
      - name: Make
        run: |
          cd build
          make -j 16
      - name: Multi-point optimization test
        run: bash .github/workflows/optim_test.sh
