name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  docker-image:
    uses: ./.github/workflows/docker.yml
  magudi-unit:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/dreamer2368/magudi/magudi_env:latest
      options: --user 1001 --privileged
    name: CPU-test
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action
        with:
          access_token: ${{ github.token }}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Cmake
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=debug -DCMAKE_Fortran_COMPILER=mpif90 ../
      - name: Make
        run: |
          cd build
          make -j 16
      - name: Unit test
        run: |
          cd build
          CTEST_OUTPUT_ON_FAILURE=TRUE make test
  optim-grad-test:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/dreamer2368/magudi/magudi_env:latest
      options: --user 1001 --privileged
    name: Optimization-gradient-test
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Cmake
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=debug -DCMAKE_Fortran_COMPILER=mpif90 ../
      - name: Make
        run: |
          cd build
          make -j 16
      - name: Multi-point optimization gradient accuracy
        run: bash .github/workflows/optim_grad_test.sh
  optim-test:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/dreamer2368/magudi/magudi_env:latest
      options: --user 1001 --privileged
    name: Optimization-test
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Cmake
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=debug -DCMAKE_Fortran_COMPILER=mpif90 ../
      - name: Make
        run: |
          cd build
          make -j 16
      - name: Multi-point optimization framework test
        run: bash .github/workflows/optim_test.sh
